##Descargamos una versión concreta de UBUNTU, a través del tag 
FROM ubuntu 
MAINTAINER Apasoft Formacion "apasoft.formacion@gmail.com" 
##Actualizamos el sistema 
RUN apt-get update 
##Instalamos Apache 
RUN apt-get install -y apache2 
##Creamos un fichero index.html en el directorio por defecto de apache 
RUN echo 'Mi primer Dockerfile' > /var/www/html/index.html 
##Arrancamos APACHE a través de CMD
CMD apachectl -D FOREGROUND 
##Exponemos el Puerto 80 
EXPOSE 80 